force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Lead_Speaker__c.field-meta.xml
<CustomField>
    <fullName>Lead_Speaker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Speaker</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Attendees with type Speaker can be selected as Lead Speaker.</errorMessage>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <value>Speaker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Sponsor__c.field-meta.xml
<CustomField>
    <fullName>Sponsor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsor</label>
    <referenceTo>Sponsor__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sponsor__c/Sponsor__c.object-meta.xml
<CustomObject>
    <label>Sponsor</label>
    <nameField>
        <label>Sponsor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sponsors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sponsor__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sponsors</relationshipLabel>
    <relationshipName>Sponsors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SponsorDashboardController.cls
public with sharing class SponsorDashboardController {

    @AuraEnabled(cacheable=true)
    public static List<Event__c> getEvents(Id sponsorId) {

        return [
            SELECT Id, Name,
                   (SELECT Id FROM Attendees__r)
            FROM Event__c
            WHERE Sponsor__c = :sponsorId
        ];
    }
}






// public with sharing class SponsorDashboardController {

//     @AuraEnabled(cacheable=true)
//     public static List<Event__c> getEvents(Id sponsorId) {

    
//         List<Event__c> eventList = [
//             SELECT Id, Name,
//                    (SELECT Id FROM Attendees__r)
//             FROM Event__c
//             WHERE Sponsor__c = :sponsorId
//         ];

//         return eventList;
//     }
// }